[workspace]
members = [
    "intuition",
    "hashsum",
]

[workspace.package]
edition = "2021"
authors = ["Cavey Cool <caveycool@gmail.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/cavemanloverboy/intuition"
